import { StyleSheet } from "react-native";
import type { Theme } from "../theme/colors";

export const createStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 16,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.background,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    headerSpacer: {
      width: 36,
    },
    title: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.text,
    },
    content: {
      padding: 16,
    },
    infoCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.backgroundSecondary,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 20,
      gap: 12,
    },
    infoContent: {
      flex: 1,
    },
    infoTitle: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.text,
      marginBottom: 4,
    },
    infoText: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 18,
    },
    infoHighlight: {
      fontWeight: "600",
      color: theme.primary,
    },
    section: {
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
    },
    sectionHeaderText: {
      flex: 1,
    },
    sectionAddButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.18,
      shadowRadius: 4,
      elevation: 3,
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.textTertiary,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 2,
    },
    sectionDescription: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 10,
    },
    locationRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 14,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 10,
    },
    locationInfo: {
      flex: 1,
    },
    locationNameRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    locationName: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.text,
    },
    shortNameBadge: {
      backgroundColor: theme.primary + "20",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    shortNameBadgeText: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.primary,
      letterSpacing: 0.5,
    },
    locationMeta: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 4,
    },
    locationActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginLeft: 12,
    },
    iconButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.background,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    emptyText: {
      fontSize: 13,
      color: theme.textTertiary,
      fontStyle: "italic",
    },
    loadingState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    loadingText: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      alignItems: "center",
      justifyContent: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      maxWidth: 400,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.text,
    },
    modalHint: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 12,
    },
    modalInput: {
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      paddingHorizontal: 14,
      height: 44,
      fontSize: 16,
      color: theme.inputText,
      textAlignVertical: "center",
    },
    modalActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    modalButton: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 12,
      borderRadius: 10,
    },
    modalButtonSecondary: {
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalButtonPrimary: {
      backgroundColor: theme.primary,
    },
    modalButtonDanger: {
      backgroundColor: theme.error,
    },
    modalButtonTextSecondary: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.textSecondary,
    },
    modalButtonTextPrimary: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.textInverse,
    },

    savingOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    savingText: {
      fontSize: 14,
      color: theme.textInverse,
      fontWeight: "600",
    },

    // Profile editing modal
    modalTabRow: {
      flexDirection: "row",
      borderRadius: 999,
      backgroundColor: theme.background,
      padding: 3,
      marginBottom: 16,
    },
    modalTab: {
      flex: 1,
      paddingVertical: 8,
      alignItems: "center",
      borderRadius: 999,
    },
    modalTabActive: {
      backgroundColor: theme.primary,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.12,
      shadowRadius: 3,
      elevation: 2,
    },
    modalTabText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.text,
    },
    modalTabTextActive: {
      color: theme.textInverse,
      fontWeight: "700",
    },
    modalFooter: {
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      marginTop: 8,
    },
    modalFooterButton: {
      alignItems: "center",
      paddingVertical: 11,
      borderRadius: 10,
      marginHorizontal: 0,
    },
    modalFooterButtonPrimary: {
      backgroundColor: theme.primary,
    },
    modalFooterButtonTextPrimary: {
      fontSize: 14,
      fontWeight: "700",
      color: theme.textInverse,
    },
    profileSection: {
      marginBottom: 16,
    },
    profileSectionTitle: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.textTertiary,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      marginBottom: 8,
    },
    profileChipScroll: {
      flexGrow: 0,
    },
    profileChipRow: {
      flexDirection: "row",
      gap: 8,
      paddingBottom: 4,
    },
    profileChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
    },
    profileChipSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    profileChipText: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    profileChipTextSelected: {
      color: theme.textInverse,
      fontWeight: "600",
    },
    profileNpkRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 8,
    },
    profileNpkLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.text,
      width: 14,
    },
    profileNpkChips: {
      flex: 1,
      flexDirection: "row",
      gap: 6,
    },
    profileNpkChip: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
    },
    profileNpkChipSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primary,
    },
    profileNpkChipText: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    profileNpkChipTextSelected: {
      color: theme.textInverse,
      fontWeight: "600",
    },
    profileDateCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 14,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: theme.borderLight,
      overflow: "hidden",
    },
    profileDateCardTouchable: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
    },
    profileDateCardIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 9,
      backgroundColor: theme.primaryLight,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
    },
    profileDateCardContent: {
      flex: 1,
    },
    profileDateCardLabel: {
      fontSize: 11,
      fontWeight: "600",
      color: theme.textTertiary,
      letterSpacing: 0.4,
      marginBottom: 2,
    },
    profileDateCardValue: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.text,
    },
    profileDateCardPlaceholder: {
      fontSize: 14,
      color: theme.inputPlaceholder,
    },
    profileNotesInput: {
      backgroundColor: theme.inputBackground,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: theme.inputText,
      minHeight: 72,
      textAlignVertical: "top",
    },
    profileStaleDateHint: {
      fontSize: 12,
      color: theme.warning,
      marginTop: 4,
    },
    profileSectionDivider: {
      height: 1,
      backgroundColor: theme.border,
      marginVertical: 12,
    },

    // Location row profile summary strip
    profileSummaryStrip: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 4,
    },
    profileBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.background,
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderWidth: 1,
      borderColor: theme.border,
      gap: 4,
    },
    profileBadgeText: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: "600",
    },
    npkDotRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    npkDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    modalContentTall: {
      maxHeight: "88%",
    },
    scrollContentPadding: {
      paddingTop: 10,
      paddingBottom: 4,
    },
    shortNameWrap: {
      marginTop: 8,
    },
  });
