import { StyleSheet } from "react-native";
import type { Theme } from "../theme/colors";

export const createWizardStyles = (theme: Theme): ReturnType<typeof StyleSheet.create> =>
  StyleSheet.create({
    root: {
      flex: 1,
    },
    wizardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 8,
      paddingVertical: 12,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    wizardDismissButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.borderLight,
    },
    wizardTitle: {
      fontSize: 17,
      fontWeight: "700" as const,
      color: theme.text,
    },
    wizardTitleRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 6,
    },
    unsavedDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.warning,
    },
    wizardHeaderSpacer: {
      width: 40,
      height: 40,
    },
    stepRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 6,
    },
    stepCol: {
      alignItems: "center",
      width: 48,
    },
    stepDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.borderLight,
      marginBottom: 5,
    },
    stepDotActive: {
      backgroundColor: theme.primary,
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    stepDotComplete: {
      backgroundColor: theme.primaryLight,
      borderWidth: 2,
      borderColor: theme.primary,
    },
    stepConnector: {
      flex: 1,
      height: 2,
      backgroundColor: theme.borderLight,
      marginTop: 4,
      alignSelf: "flex-start" as const,
    },
    stepConnectorFilled: {
      backgroundColor: theme.primary,
    },
    stepLabel: {
      fontSize: 11,
      color: theme.textTertiary,
      textAlign: "center" as const,
    },
    stepLabelActive: {
      color: theme.primary,
      fontWeight: "600" as const,
    },
    stepLabelComplete: {
      color: theme.textSecondary,
    },
    stepContent: {
      flex: 1,
    },
    stepScrollContent: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 140,
    },
    wizardNavBar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 12,
      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
    },
    wizardStepCounter: {
      flex: 1,
      fontSize: 13,
      color: theme.textTertiary,
      fontWeight: "500" as const,
    },
    wizardBackBtn: {
      height: 48,
      paddingHorizontal: 20,
      justifyContent: "center",
      alignItems: "center",
    },
    wizardBackText: {
      fontSize: 15,
      color: theme.textSecondary,
      fontWeight: "600" as const,
    },
    wizardBackSpacer: {
      width: 80,
    },
    wizardNextBtn: {
      height: 48,
      width: 80,
      backgroundColor: theme.primary,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    wizardNextText: {
      fontSize: 15,
      color: theme.buttonText,
      fontWeight: "700" as const,
    },
    wizardSaveBtn: {
      height: 48,
      flex: 1,
      backgroundColor: theme.success,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 12,
    },
    stepErrorText: {
      fontSize: 13,
      color: theme.error,
      marginTop: 4,
      marginBottom: 8,
      marginHorizontal: 4,
      fontWeight: "600" as const,
    },
    saveBanner: {
      position: "absolute" as const,
      left: 16,
      right: 16,
      backgroundColor: theme.card,
      borderRadius: 12,
      padding: 14,
      flexDirection: "row" as const,
      alignItems: "center",
      gap: 10,
      borderWidth: 1,
      borderColor: theme.primaryLight,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 6,
    },
    saveBannerText: {
      flex: 1,
      fontSize: 13,
      color: theme.text,
      lineHeight: 18,
    },
    dateCardLabelRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 6,
    },
    spaceTypeCardHint: {
      fontSize: 10,
      color: theme.textTertiary,
      marginTop: 2,
    },
    wizardSaveBtnDisabled: {
      opacity: 0.6,
    },
  });
