import { StyleSheet } from 'react-native';
import { useTheme } from '../theme';

export const createStyles = (theme: ReturnType<typeof useTheme>) => StyleSheet.create({
  // ── Standard Card ──
  card: {
    flexDirection: 'row',
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    alignItems: 'center',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  imageContainer: {
    position: 'relative',
    marginRight: 12,
  },
  image: {
    width: 64,
    height: 64,
    borderRadius: 10,
  },
  placeholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  emoji: {
    fontSize: 32,
  },
  missingImageBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  healthIndicator: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: theme.backgroundSecondary,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  name: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    flex: 1,
  },
  badge: {
    fontSize: 9,
    color: theme.accent,
    backgroundColor: theme.accentLight,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
    maxWidth: 110,
    overflow: 'hidden',
  },
  variety: {
    fontSize: 12,
    color: theme.textSecondary,
    fontStyle: 'italic',
    marginTop: 1,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    minWidth: 0,
  },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  metaText: {
    fontSize: 12,
    color: theme.textTertiary,
    flexShrink: 1,
  },
  metaDot: {
    fontSize: 12,
    color: theme.border,
    marginHorizontal: 5,
  },
  ageText: {
    fontSize: 12,
    color: theme.primary,
    fontWeight: '600',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 6,
  },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: '#e3f2fd',
    borderWidth: 1,
    borderColor: '#bbdefb',
  },
  statusChipOverdue: {
    backgroundColor: '#ffebee',
    borderColor: '#ffcdd2',
  },
  statusChipText: {
    fontSize: 11,
    color: '#2196f3',
    fontWeight: '600',
  },
  statusChipTextOverdue: {
    color: '#f44336',
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  pestStatusChip: {
    backgroundColor: '#FFEBEE',
    borderColor: '#f4433640',
  },
  pestStatusChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#f44336',
  },
  cardActions: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingLeft: 6,
  },
  cardActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardDeleteBtn: {
    backgroundColor: theme.errorLight,
  },

  // ── Compact Grid Card ──
  compactCard: {
    flex: 1,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 12,
    margin: 4,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
    overflow: 'hidden',
    position: 'relative',
  },
  healthDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: theme.backgroundSecondary,
    zIndex: 2,
  },
  compactImage: {
    width: '100%',
    aspectRatio: 1.3,
  },
  compactPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactEmoji: {
    fontSize: 36,
  },
  waterBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 2,
    zIndex: 2,
  },
  waterBadgeOverdue: {
    backgroundColor: 'rgba(255,235,238,0.95)',
  },
  waterBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#2196f3',
  },
  waterBadgeTextOverdue: {
    color: '#f44336',
  },
  pestBadgeCompact: {
    position: 'absolute',
    top: 4,
    left: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: 'rgba(255,235,238,0.95)',
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 2,
    zIndex: 2,
  },
  pestBadgeCompactText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#f44336',
  },
  compactInfo: {
    padding: 8,
    paddingTop: 6,
  },
  compactName: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text,
  },
  compactMeta: {
    fontSize: 11,
    color: theme.textTertiary,
    marginTop: 1,
  },
  compactLocation: {
    fontSize: 10,
    color: theme.textSecondary,
    marginTop: 2,
  },
  compactActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 6,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  compactActionBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: theme.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactDeleteBtn: {
    backgroundColor: theme.errorLight,
  },
});
