import { StyleSheet } from "react-native";

export const createStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    heroHeader: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 20,
      backgroundColor: theme.primary,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    heroGreeting: {
      fontSize: 28,
      fontWeight: "bold",
      color: "#fff",
    },
    heroDate: {
      fontSize: 14,
      color: "rgba(255,255,255,0.8)",
      marginTop: 4,
    },
    heroThemeToggle: {
      alignItems: "center",
      justifyContent: "center",
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(255,255,255,0.2)",
    },
    // Task Donut Card
    donutCard: {
      backgroundColor: theme.backgroundSecondary,
      paddingHorizontal: 12,
      paddingVertical: 16,
      marginTop: 1,
    },
    donutRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    donutContainer: {
      width: 140,
      height: 140,
      alignItems: "center",
      justifyContent: "center",
    },
    donutCenter: {
      position: "absolute",
      alignItems: "center",
    },
    donutPercent: {
      fontSize: 26,
      fontWeight: "bold",
      color: theme.text,
    },
    donutSubtext: {
      fontSize: 12,
      color: theme.textSecondary,
      marginTop: 1,
    },
    donutOverdue: {
      fontSize: 10,
      fontWeight: "700",
      color: theme.error,
      marginTop: 2,
    },
    // Tile grid beside donut (2 per row)
    chipColumn: {
      flex: 1,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginLeft: 14,
      alignContent: "center",
    },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 14,
      gap: 3,
      width: "47%",
    },
    chipDone: {
      opacity: 0.55,
    },
    chipOverdue: {
      borderWidth: 1.5,
      borderColor: theme.error + "70",
    },
    chipEmoji: {
      fontSize: 14,
    },
    chipText: {
      fontSize: 13,
      fontWeight: "700",
    },
    chipTextDone: {
      textDecorationLine: "line-through",
    },
    chipOverdueCount: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.error,
    },
    // Garden Health
    gardenHealthCard: {
      backgroundColor: theme.backgroundSecondary,
      marginTop: 1,
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    gardenHealthTitle: {
      fontSize: 17,
      fontWeight: "700",
      color: theme.text,
      letterSpacing: 0.3,
      marginBottom: 10,
    },
    gardenHealthRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    healthColumn: {
      flex: 1,
      alignItems: "center",
      gap: 6,
    },
    healthDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    healthCount: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.text,
    },
    healthLabel: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    healthDivider: {
      width: 1,
      height: 40,
      backgroundColor: theme.border,
    },
    // Horizontal attention cards
    alertsSection: {
      backgroundColor: theme.backgroundSecondary,
      paddingTop: 12,
      paddingBottom: 14,
      paddingLeft: 16,
      marginTop: 1,
    },
    alertCardH: {
      width: 150,
      padding: 12,
      backgroundColor: theme.errorLight,
      borderRadius: 14,
      marginRight: 10,
      borderWidth: 1,
      borderColor: theme.error + "30",
    },
    alertCardHCritical: {
      backgroundColor: theme.errorLight,
      borderColor: theme.error + "40",
    },
    alertCardHWarning: {
      backgroundColor: theme.warningLight,
      borderColor: theme.warning + "40",
    },
    alertCardHInfo: {
      backgroundColor: theme.primaryLight,
      borderColor: theme.primary + "40",
    },
    alertIconH: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.error,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    alertPlantNameH: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.text,
      marginBottom: 3,
    },
    alertTextH: {
      fontSize: 11,
      color: theme.textSecondary,
      lineHeight: 15,
    },
    // Sections
    section: {
      padding: 16,
      backgroundColor: theme.backgroundSecondary,
      marginTop: 1,
    },
    taskSection: {
      paddingVertical: 16,
      paddingLeft: 16,
      backgroundColor: theme.backgroundSecondary,
      marginTop: 1,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
      paddingRight: 16,
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: "600",
      color: theme.text,
    },
    seeAllText: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.primary,
    },
    priorityBadge: {
      backgroundColor: theme.errorLight,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.error + "40",
    },
    priorityMedium: {
      backgroundColor: theme.warningLight,
      borderColor: theme.warning + "40",
    },
    priorityText: {
      fontSize: 10,
      fontWeight: "700",
      color: theme.error,
      letterSpacing: 0.5,
    },
    // Horizontal task cards
    taskCardH: {
      width: 140,
      padding: 12,
      backgroundColor: theme.background,
      borderRadius: 14,
      marginRight: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    taskCardHOverdue: {
      borderColor: theme.error + "50",
      backgroundColor: theme.errorLight,
    },
    taskCardHTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    taskIconH: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    taskDoneBtn: {
      width: 26,
      height: 26,
      borderRadius: 13,
      borderWidth: 2,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
    },
    taskDoneBtnDone: {
      backgroundColor: theme.success,
      borderColor: theme.success,
    },
    taskTypeH: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.text,
      marginBottom: 2,
    },
    taskPlantH: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 8,
    },
    taskCardHActions: {
      flexDirection: "row",
      gap: 8,
    },
    taskActionSmall: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: theme.backgroundSecondary,
    },
    taskActionSmallText: {
      fontSize: 10,
      color: theme.textSecondary,
      fontWeight: "600",
    },
    // Vertical task cards
    taskSectionV: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: theme.backgroundSecondary,
      marginTop: 1,
    },
    taskCardV: {
      flexDirection: "row",
      backgroundColor: theme.background,
      borderRadius: 12,
      marginBottom: 8,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.border,
    },
    taskCardVBorder: {
      width: 4,
    },
    taskCardVContent: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 12,
    },
    taskCardVLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      gap: 12,
    },
    taskIconV: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    taskCardVInfo: {
      flex: 1,
    },
    taskTypeV: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.text,
    },
    taskPlantV: {
      fontSize: 13,
      color: theme.textSecondary,
      marginTop: 2,
    },
    taskCardVActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    taskDoneBtnV: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 2,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
    },
    taskActionBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
    },
    taskWrapper: {
      marginBottom: 8,
    },
    quickActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
      marginTop: 8,
    },
    actionButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    actionText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: "500",
    },
    // Empty state
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      padding: 48,
      marginTop: 48,
    },
    emptyText: {
      fontSize: 20,
      fontWeight: "600",
      color: theme.text,
      marginTop: 16,
    },
    emptySubtext: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: 4,
    },
    emptyButton: {
      marginTop: 20,
      paddingHorizontal: 24,
      paddingVertical: 12,
      backgroundColor: theme.primary,
      borderRadius: 24,
    },
    emptyButtonText: {
      color: theme.textInverse,
      fontSize: 15,
      fontWeight: "600",
    },
    // Modal
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 20,
      padding: 24,
      width: "100%",
      maxWidth: 400,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.text,
      marginBottom: 8,
    },
    modalSubtext: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 16,
    },
    modalInput: {
      backgroundColor: theme.inputBackground,
      borderRadius: 12,
      padding: 12,
      fontSize: 15,
      color: theme.inputText,
      minHeight: 80,
      textAlignVertical: "top",
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.inputBorder,
    },
    skipReasons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 20,
    },
    reasonChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: theme.primaryLight,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.primary,
    },
    reasonText: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: "500",
    },
    modalButtons: {
      flexDirection: "row",
      gap: 12,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
    },
    modalButtonCancel: {
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalButtonConfirm: {
      backgroundColor: theme.warning,
    },
    modalButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.textInverse,
    },
    modalButtonTextCancel: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.textSecondary,
    },
  });
